apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-replicaset
    release: mongodb-replicaset
  name: mongodb-replicaset-ready
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 27017
  selector:
    app: mongodb-replicaset
    release: mongodb-replicaset
  type: ClusterIP
