apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: mongodb-replicaset
    release: mongodb-replicaset
  name: mongodb-replicaset-client
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: mongodb-replicaset
    release: mongodb-replicaset
  type: ClusterIP
